# Generated by Django 4.2.20 on 2025-03-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pub_date',
        ),
    ]
